changelog_type: "commit_message"  # "pull_request"  # or "commit_message"
header_prefix: "Version "
commit_changelog: true
comment_changelog: true
version_regex: "v?([0-9]{1,2})+[.]+([0-9]{1,2})+[.]+([0-9]{1,2})+[b]+([0-9]{1,2})"
pull_request_title_regex: "^Release"
group_config:
  - title: Bug Fixes
    labels:
      - bug
      - dependencies
  - title: Code Improvements
    labels:
      - enhancement
      - refactor
  - title: Tests
    labels:
      - tests
  - title: Documentation Updates
    labels:
      - documentation
