repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: flake8
        args: [--config=setup.cfg]
    -   id: check-added-large-files
        args: ['--maxkb=300']
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: check-yaml
    -   id: requirements-txt-fixer
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    -   id: black
        # exclude: ^(build/*)
        args: [-l 120, --target-version=py38, --config=pyproject.toml]
# -   repo: https://github.com/pre-commit/mirrors-isort
#     rev: v4.3.21
    # hooks:
    # -   id: isort
    #     name: isort
    #     entry: python -m isort
    #     language: system
    #     types: [python]    
    #     language_version: python3
    #     # exclude: ^(build/*)
    #     args: [--settings-path, ./pyproject.toml]
# -   repo: https://github.com/jumanjihouse/pre-commit-hooks
#     rev: 1.11.0
#     hooks:
#     -   id: require-ascii
#         exclude: ^(examples/.*\.ipynb)
#     -   id: script-must-have-extension
#     -   id: forbid-binary
        # exclude: ^(examples/*)
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
    -   id: forbid-crlf
    -   id: forbid-tabs
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.790
#     hooks:
#     -   id: mypy    
