# This file enables examples to be run using myBinder.
# It is not part of normal installation.
name: PyKale_tutorials
channels:
- rusty1s
- pytorch
- conda-forge
- defaults
dependencies:
- cpuonly
- pip
- python==3.7
- pytorch
- pytorch-geometric
- rdkit
- torchaudio
- torchvision
- pip:
  - .
