# This workflow will run lint and many other pre-commit hooks
# https://pre-commit.com/
# We found pre-commit is not running black fully so we force black after pre-commit

name: lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint and pre-commit checks
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - name: Install dependencies
      run: |
        pip install pre-commit isort flake8==3.8.4
        pre-commit install
    - name: Run pre-commit checks including linting
      run: |
        pre-commit run --all-files
        pip install black
        black .
